server:
  port: 8001

spring:
  application:
    name: provider-ticket

eureka:
  instance:
    prefer-ip-address: true #访问路径可以显示IP地址
    instance-id: provider-ticket
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #单机 #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）